package utfpr.gui;

import java.text.DecimalFormat;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import utfpr.banco.Banco;
import utfpr.banco.ContaBancaria;
import utfpr.banco.ContaCorrente;

public class ListaSaldos extends javax.swing.JInternalFrame {

    private Banco banco;
    private static final DecimalFormat df = new DecimalFormat("0.00");

    /**
     * Creates new form ListaSaldos
     * @param banco Banco que se deseja apresentar
     */
    public ListaSaldos(Banco banco) {
        initComponents();
        remove_title_bar();
        this.banco = banco;
        carregarSaldos();
    }

    private void remove_title_bar() {
        putClientProperty("ListaClientes.isPalette", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);

    }

    public void setBanco(Banco banco) {
        this.banco = banco;
    }

    private void carregarSaldos() {
        ContaBancaria aux;

        lblMovimentacao.setText(banco.getNome());
        txtSaldoMedio.setText("R$ " + df.format(banco.getSaldoMedioContas()));
        txtSaldoMedioCC.setText("R$ " + df.format(banco.getSaldoMedioContasCorrente()));
        txtSaldoMedioCP.setText("R$ " + df.format(banco.getSaldoMedioContasPupanca()));

        aux = banco.getContaMenorSaldo();
        txtMenorSaldoValor.setText("R$ " + df.format(aux.getSaldo()));
        lblMenorSaldoTitular.setText(aux.getNumero() + " - " + aux.getTitular().getNome());
        if (aux instanceof ContaCorrente) {
            lblMenorSaldoTipo.setText("Conta corrente");
        } else {
            lblMenorSaldoTipo.setText("Conta poupança");
        }

        aux = banco.getContaMaiorSaldo();
        txtMaiorSaldoValor.setText("R$ " + df.format(aux.getSaldo()));
        lblMaiorSaldoTitular.setText(aux.getNumero() + " - " + aux.getTitular().getNome());
        if (aux instanceof ContaCorrente) {
            lblMaiorSaldoTipo.setText("Conta corrente");
        } else {
            lblMaiorSaldoTipo.setText("Conta poupança");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        lblMenorSaldoTipo = new javax.swing.JLabel();
        lblSaldoMedioCC = new javax.swing.JLabel();
        lblMaiorSaldoTitular = new javax.swing.JLabel();
        txtSaldoMedioCC = new javax.swing.JFormattedTextField();
        lblMaiorSaldo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblMaiorSaldoTipo = new javax.swing.JLabel();
        lblSaldoMedioCP = new javax.swing.JLabel();
        txtMaiorSaldoValor = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblMovimentacao = new javax.swing.JLabel();
        txtSaldoMedioCP = new javax.swing.JFormattedTextField();
        lblSaldoMedio = new javax.swing.JLabel();
        lblMenorSaldo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        txtSaldoMedio = new javax.swing.JFormattedTextField();
        lblMenorSaldoTitular = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtMenorSaldoValor = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();

        jPanel8.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        setBackground(java.awt.SystemColor.window);
        setBorder(null);

        lblMenorSaldoTipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMenorSaldoTipo.setText("Tipo");

        lblSaldoMedioCC.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSaldoMedioCC.setText("Saldo médio contas correntes");

        lblMaiorSaldoTitular.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMaiorSaldoTitular.setText("Codigo - Titular");

        txtSaldoMedioCC.setEditable(false);
        txtSaldoMedioCC.setBackground(java.awt.SystemColor.text);
        txtSaldoMedioCC.setBorder(null);
        txtSaldoMedioCC.setForeground(new java.awt.Color(255, 255, 102));
        txtSaldoMedioCC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtSaldoMedioCC.setText("R$ 0,00");
        txtSaldoMedioCC.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        lblMaiorSaldo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblMaiorSaldo.setForeground(new java.awt.Color(0, 150, 115));
        lblMaiorSaldo.setText("Conta com maior saldo");

        jPanel5.setBackground(new java.awt.Color(255, 255, 102));
        jPanel5.setPreferredSize(new java.awt.Dimension(188, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        lblMaiorSaldoTipo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMaiorSaldoTipo.setText("Tipo");

        lblSaldoMedioCP.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSaldoMedioCP.setText("Saldo médio contas poupanças");

        txtMaiorSaldoValor.setEditable(false);
        txtMaiorSaldoValor.setBackground(java.awt.SystemColor.text);
        txtMaiorSaldoValor.setBorder(null);
        txtMaiorSaldoValor.setForeground(new java.awt.Color(0, 150, 115));
        txtMaiorSaldoValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtMaiorSaldoValor.setText("R$ 0,00");
        txtMaiorSaldoValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 150, 115));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        lblMovimentacao.setBackground(new java.awt.Color(0, 0, 0));
        lblMovimentacao.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblMovimentacao.setForeground(new java.awt.Color(255, 255, 255));
        lblMovimentacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMovimentacao.setText("Movimentação");
        lblMovimentacao.setOpaque(true);

        txtSaldoMedioCP.setEditable(false);
        txtSaldoMedioCP.setBackground(java.awt.SystemColor.text);
        txtSaldoMedioCP.setBorder(null);
        txtSaldoMedioCP.setForeground(new java.awt.Color(255, 153, 51));
        txtSaldoMedioCP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtSaldoMedioCP.setText("R$ 0,00");
        txtSaldoMedioCP.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        lblSaldoMedio.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        lblSaldoMedio.setText("Saldo médio");

        lblMenorSaldo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblMenorSaldo.setForeground(new java.awt.Color(255, 0, 0));
        lblMenorSaldo.setText("Conta com menor saldo");

        jPanel7.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 131, Short.MAX_VALUE)
        );

        txtSaldoMedio.setEditable(false);
        txtSaldoMedio.setBackground(java.awt.SystemColor.text);
        txtSaldoMedio.setBorder(null);
        txtSaldoMedio.setForeground(new java.awt.Color(57, 102, 159));
        txtSaldoMedio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtSaldoMedio.setText("R$ 0,00");
        txtSaldoMedio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        lblMenorSaldoTitular.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMenorSaldoTitular.setText("Codigo - Titular");

        jPanel2.setBackground(new java.awt.Color(57, 102, 159));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        txtMenorSaldoValor.setEditable(false);
        txtMenorSaldoValor.setBackground(java.awt.SystemColor.text);
        txtMenorSaldoValor.setBorder(null);
        txtMenorSaldoValor.setForeground(new java.awt.Color(255, 51, 0));
        txtMenorSaldoValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.###"))));
        txtMenorSaldoValor.setText("R$ 0,00");
        txtMenorSaldoValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(4, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMovimentacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSaldoMedio)
                            .addComponent(txtSaldoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtSaldoMedioCC, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSaldoMedioCC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtSaldoMedioCP, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSaldoMedioCP)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMenorSaldoTitular)
                            .addComponent(lblMenorSaldoTipo)
                            .addComponent(lblMenorSaldo)
                            .addComponent(txtMenorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMaiorSaldo)
                            .addComponent(lblMaiorSaldoTitular)
                            .addComponent(lblMaiorSaldoTipo)
                            .addComponent(txtMaiorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMovimentacao)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSaldoMedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSaldoMedioCC, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoMedioCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSaldoMedioCP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSaldoMedioCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMenorSaldo)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblMenorSaldoTitular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMenorSaldoTipo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMenorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMaiorSaldo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblMaiorSaldoTitular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMaiorSaldoTipo)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtMaiorSaldoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        lblMovimentacao.getAccessibleContext().setAccessibleDescription("Movimentação");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblMaiorSaldo;
    private javax.swing.JLabel lblMaiorSaldoTipo;
    private javax.swing.JLabel lblMaiorSaldoTitular;
    private javax.swing.JLabel lblMenorSaldo;
    private javax.swing.JLabel lblMenorSaldoTipo;
    private javax.swing.JLabel lblMenorSaldoTitular;
    private javax.swing.JLabel lblMovimentacao;
    private javax.swing.JLabel lblSaldoMedio;
    private javax.swing.JLabel lblSaldoMedioCC;
    private javax.swing.JLabel lblSaldoMedioCP;
    private javax.swing.JFormattedTextField txtMaiorSaldoValor;
    private javax.swing.JFormattedTextField txtMenorSaldoValor;
    private javax.swing.JFormattedTextField txtSaldoMedio;
    private javax.swing.JFormattedTextField txtSaldoMedioCC;
    private javax.swing.JFormattedTextField txtSaldoMedioCP;
    // End of variables declaration//GEN-END:variables
}